// Almanach Mařeny — sloučení původního manuálu a komentářů ročníku 2024 do jednoho
// dokumentu. Obsah sekcí je sloučen z obou zdrojových dokumentů.

export type CalloutKind = "tip" | "pozor" | "kontakt";

export interface Callout {
  kind: CalloutKind;
  text: string;
}

export interface AlmanachSection {
  id: string;
  emoji: string;
  title: string;
  intro: string;
  tips: string[];
  callouts: Callout[];
}

export const ALMANACH: AlmanachSection[] = [
  {
    id: "uvod",
    emoji: "🎪",
    title: "Co je Mařena",
    intro:
      "Čtete-li tenhle almanach, rozhodli jste se (snad dobrovolně) zorganizovat tu nejlepší, nejšílenější a zároveň nejnáročnější studentskou akci na Fakultě architektury VUT v Brně. Mařena je týdenní (cca 7-10 dní) festival na přelomu září a října, dokud je ještě teplo: nabitý přednáškami, programem, koncerty a barem na dvoře, zakončený průvodem městem a křtem prváků na Flédě. Tahle příručka slučuje původní manuál s poznámkami ročníku 2024, aby vám příští ročník ušetřil část těch stovek emailů, schůzek a nervů. A na úvod jedno motto, kterým se řiďte: kolik Mařeny je dost Mařeny? Mařeny není nikdy dost.",
    tips: [
      "Mařena je studentská akce, kterou fakulta jen zastřešuje. To je důležité držet v hlavě úplně všude: zprávy přednášejícím, sponzorům i úřadům posíláte za sebe / za tým Mařeny, NE za fakultu.",
      "Termín: nejčastěji přelom září a října (ještě je teplo), délka cca 7-10 dní. Týden plný přednášek, programu a baru vrcholí posledním dnem průvodem městem a křtem prváků na Flédě.",
      "Kostra týdne: přes den obědy a doprovodný program, podvečer speciální přednášky, večer koncerty a DJs na dvoře a v Arše. Poslední den průvod městem zakončený pasováním prvního ročníku na Flédě.",
      "Začněte plánovat brzy. Původně doporučeno už v letním semestru s finišem přes prázdniny; ročník 2024 začal řešit na přelomu prosince a ledna. Klíčové je co nejdřív zamluvit Flédu a vyřešit datum.",
      "Rozdělte si role: organizátor, ekonom (finance ať drží jedna důvěryhodná osoba, na kterou je psaný účet), kapelník, výzdobář, kuchař, bavič. Spousta lidí říká, že organizovat nechce, ale při Mařeně pomůže, a to je v pořádku, ono to zafunguje.",
      "Organizace běží hlavně online (lidi bývají na praxích i mimo republiku). Ročník 2024 jel přes messenger skupinu (36 lidí, na schůzkách s bídou 8); o důležitém se hlasovalo ve skupině a zápisy ze schůzí se posílaly všem.",
      "POZOR NA SOUBĚH AKCÍ při volbě termínu: Designblok, Hudba z FEKTu, Den architektury, Cena Bohuslava Fuchse.",
      "Spojku na fakultě si hýčkejte. NEJDŮLEŽITĚJŠÍ ČLOVĚK je Soňa Lisoňová (supaspicybois jí říkají 'teta') - milá, ochotná, zařídí tablety, dataprojektory, zvukaře na celý festival placeného školou, banner na fasádu i kapelu na zahájení semestru. Ozvat se jí, až bude datum a nahozený program.",
      "Mařena je extrémně náročná: půl roku plánování, stovky emailů, složky na Google Disku, a po startu i fyzicky náročná. Delegujte úkoly, domluvte směny, připravte věci dopředu (posty, grafiky), jezte víc než oběd a pivo, a hlavně si to užijte, je to sranda.",
      "Bez auta ani ránu, na nákupy i provoz (parkování na dvoře po domluvě s vrátnicí).",
      "Tohle je referenční příručka pro příští ročník: jsou v ní osvědčené postupy, konkrétní jména, čísla, kontakty i to, co se ročníku 2024 nepovedlo, ať to nemusíte zkoušet znova. Detaily k přípravě, financím, programu, průvodu a Flédě najdete v dalších sekcích.",
    ],
    callouts: [
      { kind: "tip", text: "Motto, které řekněte prvákům i sobě: 'Kolik Mařeny je dost Mařeny? Mařeny není nikdy dost.' První slovo, které prvák na fakultě uslyší, musí být Mařena." },
      { kind: "kontakt", text: "Soňa Lisoňová - klíčová spojka na fakultě, zařídí techniku, zvukaře, banner i pomoc s organizací. Ozvat se, jakmile máte datum a nahozený program." },
      { kind: "pozor", text: "Mařena je STUDENTSKÁ akce, fakulta ji jen zastřešuje. Veškerou komunikaci ven (přednášející, sponzoři, úřady) posílejte za tým Mařeny, nikdy za fakultu." },
    ],
  },
  {
    id: "priprava",
    emoji: "🗓️",
    title: "Příprava a načasování",
    intro:
      "Rozhodli jste se (snad dobrovolně) zorganizovat tu nejlepší, nejšílenější a nejnáročnější studentskou akci na fakultě. Gratulujeme a kondolujeme zároveň. Mařena je půlroční maraton, a první pravidlo zní jednoduše: čím dřív začnete, tím míň budete na konci trpět. Tahle sekce je o tom, kdy zaseknout kotvy, jak dát dohromady partu, která reálně dorazí na schůzku, a v jakém pořadí řešit, co nejvíc hoří.",
    tips: [
      "Začněte plánovat už v letním semestru a finišujte přes prázdniny. Ročník 2024 se reálně rozjel na přelomu prosince a ledna - hlavní úkol hned na začátku: zamluvit Flédu co nejdřív a vyřešit datum.",
      "Termín Mařeny bývá nejčastěji na přelomu září a října (ještě je teplo), délka cca 7-10 dní. Datum a nahozený program si pohlídejte včas, protože se od nich odvíjí všechno ostatní.",
      "POZOR NA SOUBĚH AKCÍ: hlídejte si Designblok, Hudbu z FEKTu, Den architektury a Cenu Bohuslava Fuchse, ať vám termín nekoliduje.",
      "Organizace klidně celá online - lidi jsou na praxích i mimo republiku. Ročník 2024 si založil messenger skupinu (přejmenovaná ze skupiny z Pleshe). O důležitých rozhodnutích se hlasovalo ve skupině a zápisy ze schůzí se posílaly všem.",
      "Realita účasti: ve skupině bylo 36 lidí, na online schůzku jich s bídou dorazilo 8. Lidi rádi kecají do rozhodování, ale na samotnou organizaci hůř - počítejte s tím a nezakládejte plán na tom, že přijdou všichni.",
      "2x se osvědčilo poslat hromadný email ve stylu 'kdo se chce účastnit organizace, ať napíše, jinak ať mlčí navždy'. Spousta lidí řekla, že organizovat nechtějí, ale při Mařeně pomůžou - a pomohli, bylo to super.",
      "Rozdělte si role hned na začátku: organizátor, ekonom, kapelník, výzdobář, kuchař, bavič a tak dál.",
      "Pořadí domlouvání programu podle toho, co nejvíc hoří: nejdřív KAPELY (domlouval ten, kdo navrhl nebo kapelu znal - často z maškaráku/Pleshe), pak PŘEDNÁŠEJÍCÍ (dlouhý proces - poslední domluvená dorazila až 2 týdny před festivalem), a nakonec TÉMA (ať se na něm může začít dělat grafika).",
      "Přednášející piště co nejdřív: zahraniční minimálně půl roku dopředu, české 2-3 měsíce předem. Je to dlouhý proces, neodkládejte ho.",
      "Na schůzky studentstva s děkanem choďte a informujte o termínu. Děkan slibuje hory doly (neberte vážně), ale Mařenu miluje - musí napsat na vrátnici o otevření fakulty do půlnoci a déle, jinak vás vrátný vyhodí.",
      "Nejdůležitější člověk z fakulty je Soňa Lisoňová (Supaspicybois jí říkají 'teta') - milá, ochotná, zařídí prakticky vše. Ozvěte se jí ale až budete mít datum a nahozený program.",
      "Mařena je extrémně psychicky náročná: půl roku plánování, stovky emailů a složky na Google disku. Domluvte si směny a zařiďte věci dopředu (posty, grafiky), ať se stihnete vyspat - delegujte úkoly a začněte včas, ať to není peklo.",
    ],
    callouts: [
      { kind: "tip", text: "Nejdřív kapely, pak přednášející, nakonec téma - v tomhle pořadí to nejmíň hoří." },
      { kind: "pozor", text: "Plánujte na realitu, ne na ideál: ze 36 lidí ve skupině dorazí na schůzku tak 8. Ti, co řeknou, že nechtějí organizovat, ale pomůžou při Mařeně, většinou opravdu pomůžou." },
      { kind: "kontakt", text: "Soňa Lisoňová (fakulta) - ozvěte se až bude datum a nahozený program. Datum a Fléda se řeší úplně první." },
    ],
  },
  {
    id: "tym",
    emoji: "🧑‍🤝‍🧑",
    title: "Tým, role a rozhodování",
    intro:
      "Mařena stojí a padá s tím, jak si rozdělíte práci a jak spolu mluvíte. Realita ročníku 2024: ve skupině bylo 36 lidí, na online schůzku jich dorazilo s bídou 8, a spousta lidí předem řekla, že organizovat nechtějí, ale při akci pomůžou. A pomohli, bylo to super. Počítejte s tím, že lidi rádi kecají do rozhodování, ale na samotnou organizaci jich je vždycky míň. Tady je osvědčený model, jak tým postavit, jak se domlouvat a jak delegovat, aby vás to nesemlelo.",
    tips: [
      "Hned na začátku si rozdělte role: organizátor, ekonom, kapelník, výzdobář, kuchař, bavič. Plánovat začněte v letním semestru a finišujte přes prázdniny; v praxi ročník 2024 řešil věci už na přelomu prosince a ledna (hlavně zamluvit Flédu a datum co nejdřív).",
      "Komunikujte přes messenger skupinu. V roce 2024 ji jen přejmenovali z Pleshe/Maškaráku, takže lidi už byli pohromadě. Hodí se to i proto, že část lidí je na praxích nebo mimo republiku, takže skoro vše běží online.",
      "O důležitých rozhodnutích hlasujte přímo ve skupině a informace ze schůzí posílejte všem, ať i ti, co na schůzku nepřišli, vědí, na čem jste se dohodli. Sdílené složky a zápisy si držte na Google disku.",
      "Počítejte s tím, že online schůzky budou prořídlé (z 36 lidí dorazilo cca 8). Lidi rádi mluví do rozhodování, ale na realizaci jich je míň, tak s tím dopředu počítejte při dělbě práce.",
      "Když potřebujete probrat tým, pošlete hromadný email ve stylu „kdo se chce účastnit organizace, ať napíše, jinak ať mlčí navždy“. V roce 2024 ho poslali dvakrát a fungovalo to.",
      "Nesnažte se do organizace zapojit úplně každého. Spousta lidí řekne, že organizovat nechtějí, ale při samotné Mařeně pomůžou na místě, a to je naprosto v pořádku. Tahle skupina „pomůžu až při akci“ je zlatá.",
      "Finance svěřte jedné důvěryhodné osobě, a to té, na kterou je psaný účet. Nemíchejte do peněz celý tým, ať v tom není bordel.",
      "Jídlo a pití (hlavně provoz baru a alkohol) si musí vzít na starost někdo vysoce kompetentní. Je to citlivá zóna kvůli školnímu řádu, takže to nedávejte komukoli.",
      "Výběr programu řešte podle toho, co nejvíc hoří: nejdřív kapely (domlouval ten, kdo je navrhl nebo znal), pak přednášející (dlouhý proces, poslední se domluvil 2 týdny před festivalem), nakonec téma a grafika.",
      "U výzdoby se osvědčilo rozdělit školu do zón pod společnou ideou, každou zónu řeší jiná skupinka. Každé skupince dejte budget; co je nad budget, jde k diskuzi.",
      "Před akcí všichni organizátoři podepíší formulář BOZP (zašle pan Hasala). Na průvod městem potřebujete minimálně 2 označené organizátory v oranžových vestách, a ten, kdo průvod zařizuje, za něj zodpovídá (má u sebe telefon).",
      "Během festivalu jasně domluvte směny (kdo a kdy je za barem, kdo ráno chystá snídaně) a zařiďte věci dopředu (posty, grafiky), ať se vyspíte. Delegujte úkoly, jezte víc než jen oběd a pivo, a hlavně si to užijte, je to sranda.",
    ],
    callouts: [
      { kind: "tip", text: "Připomínka pro klid v duši: „kolik Mařeny je dost Mařeny? Mařeny není nikdy dost.“ Mařena je extrémně psychicky náročná (půl roku plánování, stovky emailů), takže delegování není slabost, ale nutnost." },
      { kind: "pozor", text: "Lidi rádi rozhodují, ale méně realizují. Nespoléhejte na účast na online schůzkách (z 36 jich dorazí cca 8) a klíčové věci si pojistěte hlasováním ve skupině plus rozesláním zápisu všem." },
    ],
  },
  {
    id: "fakulta",
    emoji: "🏛️",
    title: "Komunikace s fakultou",
    intro:
      "Mařena je STUDENTSKÁ akce, fakulta ji \"jen\" zastřešuje. To znamená, že všechno píšete a domlouváte za sebe / za tým Mařeny, ne za fakultu. Klíčoví lidé jsou tři: děkan (Mařenu miluje, slibuje hory doly, ale hlavně musí napsat na vrátnici, ať vás v noci nevyhodí), tajemník (provoz a možný příspěvek) a hlavně Soňa Lisoňová, bez které se Mařena prakticky neobejde. Fakulta je nejradši, když od ní nechcete peníze, ale s technikou a provozem umí strašně pomoct, když víte, na koho se obrátit.",
    tips: [
      "Soňa Lisoňová je NEJDŮLEŽITĚJŠÍ člověk z fakulty. Je milá, ochotná a vše zařídí: tablety, dataprojektory, držáky na telefony, zvukaře na celý festival placeného školou, banner na fasádu i kapelu při zahájení semestru. Supaspicybois jí říkají \"teta\". Ozvěte se jí, až budete mít datum a nahozený program.",
      "Soňa také ví, komu rozesílat newsletter a osobní pozvánky (studenti, akademici, vrátnice, školníci, technici), a s ní se domlouvá dopolední slot v aule pro úvodní prezentaci prvákům. Když nevíte, koho oslovit, ptejte se Soni.",
      "Děkan: choďte na schůzky studentstva s děkanem a informujte ho o termínu. Mařenu miluje a slibuje hory doly (neberte úplně vážně), ale jedna konkrétní věc je zásadní - musí napsat na vrátnici o otevření fakulty do půlnoci a déle, jinak vás vrátný vyhodí.",
      "Tajemník: s ním řešte organizaci provozu. V roce 2024 byl nový; předchozí toho moc nesliboval (jen možný příspěvek na přednášející nebo na něco, co vydrží). Přes tajemníka jde \"ke schválení\" i plán výzdoby a způsob cenění v kuchyni - oficiálně se ve škole prodávat nesmí, takže se ceny uvádějí třeba v \"žetonech\" (dle tajemníka).",
      "Organizaci akce řešte ve spolupráci s fakultou (tajemník, děkan, proděkan), ale pamatujte: zprávy posíláte ZA SEBE / ZA TÝM MAŘENY, NIKDY ZA FAKULTU. Je to studentská akce, fakulta ji jen zastřešuje. Stejné pravidlo platí i u oslovování přednášejících a sponzorů.",
      "Peníze od fakulty: fakulta je nejradši, když od ní žádné nechcete. Dá se to bez její finanční podpory - v roce 2024 platili vše ze svého, schovávali účtenky, zapisovali výdaje a po Mařeně udělali vyúčtování.",
      "Příjezdy externistů (přednášejících) hlaste na vrátnici - email na vrátnici a kopii tajemníkovi.",
      "Provozní režim školy: běžně se škola obývá 6:00-22:00 (fakulta + nádvoří), výjimečně v rámci Mařeny do 24:00-01:00; po 22:00 jen ve studentském klubu / Arše. Po 22:00 se venku nekoncertuje (noční klid). Vrátný vás stejně o půlnoci vyhodí, takže poslední odchází po zametení dvora.",
      "BOZP řešte s panem Hasalou (pošle a podepíše se formulář BOZP - podepisují ho všichni organizátoři). Pravidla: nepolepovat a nezakrývat sochy, prodejní automaty, elektrické skříně, hydranty a hasicí přístroje (nepřemisťovat), dveře, vrátnici, auta ani schodiště; průchod min. 2 m, ideálně nehořlavé materiály, výtahy nechat volné.",
      "Aulu zamlouvejte u Forteho (hodí ji do rozvrhu). Pozor na sbor (zkouší na fakultě - v 2024 šlo o sbor pana Ocetka, dejte vědět dopředu). Přednášky by neměly omezovat výuku.",
      "Auto na dvoře: parkování na dvoře se domlouvá na vrátnici. Bez auta ani ránu.",
      "Zveřejněte program pro kantory a vedení, posílejte denní newsletter (učitelé to ocenili - tři profesoři děkovali) a před festivalem rozešlete osobní pozvánky akademikům. Komu přesně, ví Soňa.",
    ],
    callouts: [
      { kind: "kontakt", text: "Soňa Lisoňová - nejdůležitější kontakt na fakultě. Zařídí tablety, dataprojektory, zvukaře placeného školou, banner na fasádu i kapelu na zahájení. Ozvat se, až bude datum a nahozený program." },
      { kind: "pozor", text: "Děkan MUSÍ napsat na vrátnici o otevření fakulty do půlnoci a déle - jinak vás vrátný vyhodí." },
      { kind: "tip", text: "Píšete vždy ZA TÝM MAŘENY, ne za fakultu - je to studentská akce. A fakulta je nejradši, když od ní nechcete peníze." },
    ],
  },
  {
    id: "finance",
    emoji: "💰",
    title: "Finance",
    intro:
      "Mařena se dá utáhnout i bez peněz od fakulty - ta je totiž nejradši, když po ní nic nechcete. Celá ekonomika stojí na jednom společném účtu, třídním vkladu jako polštáři a na tom, že všichni poctivě platí všechno a schovávají účtenky. Klíč k tomu, aby z toho nebyl bordel, je jednoduchý: peníze řeší jedna důvěryhodná osoba a na konci se to celé sečte. Když festival vydělá, vklady se vrací - a obvykle vydělá.",
    tips: [
      "Společný účet veďte na jednu důvěryhodnou osobu - ideálně tu, na koho už je psaný (ročník 2024 jel na soukromém účtu spolužačky založeném ještě od prváku, z Maškaráku/Pleshe). Tahle osoba ať drží finance celé Mařeny, ať se to netříští.",
      "Vyberte třídní vklad - osvědčená částka je 1500 Kč od každého (původní manuál uvádí 500-1000 Kč, ročník 2024 jel na 1500). Vklad lze posílat na víckrát, ať to lidi nebolí.",
      "Počítejte s upomínáním: zaveďte zhruba 3 upozorňovací kola, a když to nezabere, přejděte na soukromé zprávy a mírný psychický nátlak. Lidi většinou nezapomenou schválně, jen zapomenou.",
      "Berte vklad jako polštář, ne jako příjem - slouží jen pro případ, že se festival sám nevydělá. Když Mařena vydělá (a obvykle vydělá), vklad se vrací celý zpátky.",
      "Fakulta je nejradši, když od ní peníze nechcete - a dá se to bez její podpory zvládnout. Případný příspěvek (např. na přednášející nebo na něco, co vydrží) řešte s tajemníkem, ale nespoléhejte na něj.",
      "Platte ze svého a pak vyúčtujte: všechno se platí z vlastní kapsy, pečlivě schovávejte VŠECHNY účtenky a průběžně zapisujte výdaje. Po Mařeně se udělá jedno společné vyúčtování.",
      "Nastavte oba způsoby placení - QR kód i hotovost. Lidi platí různě, ať máte pokryté obojí.",
      "Na QR platby použijte AlienPay z dílny pana Vostala - webová stránka generuje QR kódy a částka se mění přímo na straně kasy. Pan Vostal je ochotný to nasdílet.",
      "Hotovostní kasu zakládejte se základem na další den - jako v hospodě. Ráno máte z čeho vracet, večer se to dorovná.",
      "Domluvte se, že si všichni platí všechno - pití, jídlo i merch. Žádné výjimky a dluhy na potom, jinak je z toho v kase i ve vztazích bordel.",
      "Kasy v praxi běžely na tabletech (zařídí škola přes Soňu Lisoňovou) - hodí se to propojit s QR platbami i hotovostní kasou na jednom místě, ideálně na velkém baru na dvoře, kde se prodává úplně všechno.",
      "Sponzoři umí ušetřit z rozpočtu hodně: peníze i věcné dary. Ročník 2024 dostal dřevo na bar, kafe od The Roses a pivní speciály. Pište z mařena emailu jako STUDENTSKÁ akce, 95 % neodpoví - nenechte se odradit.",
    ],
    callouts: [
      { kind: "tip", text: "Zlaté pravidlo proti chaosu: jedna důvěryhodná osoba drží účet i finance, všichni si platí všechno a každá účtenka se schová. Vyúčtování se dělá až po festivalu, najednou." },
      { kind: "kontakt", text: "QR platby - AlienPay z dílny pana Vostala (generátor QR kódů, ochotně nasdílí). Tablety na kasy zařídí přes školu Soňa Lisoňová." },
      { kind: "pozor", text: "Třídní vklad je jen polštář pro případ, že festival neprodělá - není to ztracená částka. Když Mařena vydělá, vrací se celý. To lidem říkejte hned při výběru, ať platí bez řečí." },
    ],
  },
  {
    id: "sponzori",
    emoji: "🤝",
    title: "Sponzoři",
    intro:
      "Sponzoři dokážou ulehčit rozpočet a přinést věci, které byste jinak platili ze svého. Realita je ale taková, že 95 % oslovených vám neodepíše a nikdy se nedozvíte proč. Neberte si to osobně a nenechte se odradit. Stačí těch pár, co řeknou ano, a najednou máte dřevo na bar, kafe na celý festival a pivní speciály k tomu.",
    tips: [
      "Oslovujte z mařena emailu a vždy zdůrazněte, že jde o STUDENTSKOU akci. Fakulta vás jen zastřešuje, píšete za sebe / za tým Mařeny, ne za fakultu.",
      "Počítejte s tím, že cca 95 % oslovených vůbec neodpoví. Je to normální, není to o vás, prostě posílejte dál a nenechte se odradit.",
      "Sponzoři mohou pomoct penězi i věcnými dary. Často je věcný dar snazší ujednat než finanční příspěvek.",
      "Osvědčené dary z ročníku 2024: dřevo na bar, kafe od The Roses a pivní speciály. Tyhle konkrétní věci reálně dorazily a posloužily.",
      "The Roses byli spokojení a chtějí sponzorovat i další ročník, takže je rozhodně oslovte znovu jako prvního jistého partnera.",
      "Oslovujte raději s předstihem, ať máte čas na to, že většina neodpoví a vy musíte zkoušet dál.",
      "Co se nepodaří sehnat od sponzorů, počítejte, že zaplatíte ze svého. V ročníku 2024 fungovala disciplína: schovávat účtenky, zapisovat výdaje a po Mařeně udělat vyúčtování.",
      "Třídní vklad slouží jako finanční polštář pro případ, že festival nepokryjí sponzoři ani výdělek. Když se vydělá, vklad se vrací celý.",
    ],
    callouts: [
      { kind: "kontakt", text: "The Roses: ověřený sponzor kafe z ročníku 2024, sami projevili zájem pokračovat i příští rok. Oslovte je jako první." },
      { kind: "tip", text: "Pište z mařena emailu a vždy hned na začátku napište, že jde o studentskou akci. Lidé reagují vstřícněji, když vědí, že za tím nestojí korporát." },
      { kind: "pozor", text: "95 % oslovených neodpoví. Nepřemýšlejte nad tím, neberte to osobně a jednoduše oslovte další firmy." },
    ],
  },
  {
    id: "propagace",
    emoji: "📣",
    title: "Propagace a sítě",
    intro:
      "Mařena žije z toho, jestli o ní lidi vědí. A věřte nevěřte: i když máte plakáty po celé škole a připnutý post na Instagramu, stejně se vás každý den někdo zeptá, co že se to vlastně děje. Propagaci proto neberte jako jednorázový plakát, ale jako každodenní práci od června až do posledního dne festivalu. Tahle sekce shrnuje, kdy začít, jak zapřáhnout grafika, proč všechno psát dvojjazyčně a jak fungoval denní newsletter, který si chválili i profesoři.",
    tips: [
      "Začněte propagovat už od června, kdy probíhá zápis prváků. Instagram předejte dál (nový ročník přebírá účet) a včas založte facebookovou událost.",
      "Člověk, který dělá grafiku, ať rovnou řeší i sociální sítě, nebo aspoň vytvoří šablony pro příspěvky. Ušetří to čas i nervy během festivalu.",
      "Připravte co nejvíc příspěvků DOPŘEDU: programy i medailonky přednášejících. V roce 2024 to neudělali, nestíhali a na medailonky úplně zapomněli, tak se z toho poučte.",
      "Házejte program KAŽDÝ DEN. I přes plakáty a připnutý post lidi pořád nevědí, co se děje, takže denní připomínka je nutnost. Denní program zveřejňujte na Instagramu, Facebooku i plakátech a sdílejte ho i s kantory.",
      "Všechno pište ČESKY I ANGLICKY. Důvod: nový bakalářský program v angličtině (13 studentů) a studenti z Erasmu. Dvojjazyčnost se týká i programu a popisků.",
      "Posílejte DENNÍ newsletter: rekapitulace dne, poděkování a pozvánka na další den. Učitelé to fakt ocenili (děkovali tři profesoři).",
      "Newsletter rozesílejte studentům, akademikům, na vrátnici, školníkům a technikům. Komu přesně, ví Soňa Lisoňová.",
      "Před festivalem pošlete akademikům osobní pozvání, ne jen hromadnou propagaci.",
      "Plakáty vylepte nejen po škole, ale i po Brně a do kaváren. BeMařena (plakáty/tisk) jde zařídit přes dílnu pana Chowaniece.",
      "Nejdůležitější člověk z fakulty pro propagaci i techniku je Soňa Lisoňová: milá, ochotná, vše zařídí (tablety, dataprojektory, držáky na telefony, zvukař na celý festival placený školou, banner na fasádu, kapela při zahájení semestru). Supaspicybois jí říkají teta. Ozvěte se jí, až budete mít datum a nahozený program.",
      "Sponzorům a přednášejícím pište z mařena emailu a vždy zdůrazněte, že je to STUDENTSKÁ akce (fakulta jen zastřešuje). Počítejte s tím, že cca 95 % neodpoví, ale nenechte se odradit.",
      "Na prváky valte Mařenu ze všech stran: první slovo na fakultě musí být Mařena. Cpěte QR kód na Instagram, opakujte informace o snídaních, obědech i večerních programech na dvoře a klidně k tomu přidejte heslo: Kolik Mařeny je dost Mařeny? Mařeny není nikdy dost.",
    ],
    callouts: [
      { kind: "tip", text: "Šablony pro sociální sítě a předem připravené medailonky jsou rozdíl mezi klidným festivalem a paniku. Co jde udělat v létě, nedělejte v týdnu Mařeny." },
      { kind: "kontakt", text: "Soňa Lisoňová (teta) zařídí techniku, banner na fasádu i to, komu rozesílat newsletter. Ozvat se až s datem a nahozeným programem." },
      { kind: "pozor", text: "Plakáty ani připnutý post nestačí. Lidi stejně nevědí, co se děje, takže program házejte na sítě každý den a všechno dvojjazyčně CZ+EN kvůli anglickému programu i Erasmu." },
    ],
  },
  {
    id: "program",
    emoji: "🎓",
    title: "Program a přednášející",
    intro:
      "Srdce Mařeny jsou večerní přednášky a večerní program na dvoře a v Arše. Klíč je začít včas: zahraniční přednášející se shánějí extrémně dlouho, kapely vychází z party, kterou už znáte z Maškaráku/Pleshe, a celý denní program se sype na lidi hlavně přes socky. Pravidlo zní jednoduše: výběr do programu řešte podle toho, co nejvíc hoří. Nejdřív kapely, pak přednášející (nejdelší proces, poslední se v roce 2024 domluvila dva týdny před festivalem), nakonec téma, ať se může dělat grafika. A nezapomeňte: kolik Mařeny je dost Mařeny? Mařeny není nikdy dost.",
    tips: [
      "Přednášející shánějte s velkým předstihem: zahraniční minimálně půl roku dopředu, české 2-3 měsíce (čím dřív, tím líp). Je to dlouhý proces, počítejte s tím.",
      "Přednášejícím nabídněte reklamní předměty, ubytování (hotel Austerlitz, Continental nebo koleje VUT - pro fakultu nižší ceny), dopravu a příspěvek na dopravu / proplacení nákladů max 1500 Kč. Honoráře a cesťáky ale ve výsledku stejně platíte vy ze svého, počítejte s tím v rozpočtu.",
      "Zprávy přednášejícím i sponzorům pište VŽDY za sebe / za tým Mařeny, NE za fakultu. Je to studentská akce, fakulta ji jen zastřešuje.",
      "Příjezdy externistů hlaste na vrátnici (email na vrátnici + kopie tajemníkovi).",
      "Sloty: max 2-3 přednášky denně, nejdřív od 17:00, délka cca 45 min. Vyznačte si atraktivní vs. méně atraktivní dny a časy - líp se to plánuje, když už máte rozvrh na zimní semestr (ten je ale často až v září, takže se nejspíš bude improvizovat).",
      "Aulu zamluvte u pana Forteho - hodí přednášky rovnou do rozvrhu. Klasika je velká AULA, alternativy jsou zasedačka v přízemí nebo malá aula A/118.",
      "Přednášky nesmí omezovat výuku. POZOR na sbor (Vox Iuvenalis, kontakt pan Ocetek) - zkouší na fakultě, dejte mu vědět dopředu.",
      "Zveřejněte program pro kantory a vedení; denní program házejte KAŽDÝ DEN na instagram, plakáty i FB. I tak lidi stejně často nevědí, co se děje - opakování je nutnost.",
      "Připravte si medailonky přednášejících a programy předem - ušetří to čas a nervy. V roce 2024 to neudělali, nestíhali a na medailonky zapomněli.",
      "VŠE česky i anglicky - kvůli novému bakalářskému programu v angličtině (13 studentů) a studentům z Erasmu.",
      "Večerní program po přednáškách běží na dvoře a v Arše: kapely a DJs. Ty obvykle znáte z Maškaráku/Pleshe, domlouvá je ten, kdo je navrhl nebo zná. Nebojte se i jiného programu než jen živá hudba. Fakulta má částečně použitelnou aparaturu a stany pro kapely.",
      "POZOR na program v Arše - v roce 2024 tam při party ukradli tablet a DJovi světla. Program v Arše proto NEDOPORUČUJEME; Archa ať slouží jako zázemí (zázemí kuchyně) a kompletně se uklidí.",
      "Doprovodný program: Vlaštovkiáda (druháci pořádají pro prváky soutěž o nejdál letící vlaštovku), Formát 400 (přednášky studentů z Erasmu, seznam je na studijním), workshopy, dílny, promítání a fašák (blešák/výměna oblečení).",
      "Motivujte prváky chodit na přednášky - osvědčil se systém razítek a odměn. A pozvěte je už na úvodní prezentaci první den (prváci mají dopolední program v aule - slot domluvte se Soňou).",
      "Po 22:00 se venku nekoncertuje kvůli nočnímu klidu - hudba pak může běžet v Arše.",
      "Režim školy: pro Mařenu lze fakultu a nádvoří obývat výjimečně do 24:00-01:00 (jinak běžně 20:00-22:00). Pozor: děkan musí napsat na vrátnici, aby fakulta byla otevřená do půlnoci a déle, jinak vás vrátný vyhodí.",
    ],
    callouts: [
      { kind: "kontakt", text: "Soňa Lisoňová je nejdůležitější člověk z fakulty - milá, ochotná, zařídí prakticky vše: tablety, dataprojektory, držáky na telefony, zvukaře na celý festival placeného školou, banner na fasádu i kapelu při zahájení semestru. Ozvěte se jí, až budete mít datum a nahozený program. Aulu řešte u pana Forteho, sbor u pana Ocetka." },
      { kind: "tip", text: "Výběr do programu řešte podle toho, co nejvíc hoří: nejdřív kapely, pak přednášející (nejdelší proces - poslední se v roce 2024 domluvila dva týdny před festivalem!), nakonec téma, ať se může dělat grafika." },
      { kind: "pozor", text: "Otevření fakulty do půlnoci+ NENÍ samozřejmost - musí ho děkan explicitně nahlásit na vrátnici. Bez toho vás vrátný v 20:00-22:00 vyhodí." },
    ],
  },
  {
    id: "vyzdoba",
    emoji: "🎨",
    title: "Výzdoba",
    intro:
      "Výzdoba je to, co z holé fakulty udělá Mařenu. Vymyslete jednu společnou ideu, rozdělte školu na zóny a každou nechte v rukou jiné partičky. Než ale popadnete izolepu, mějte na paměti dvě věci: plán musí projít schválením a pan Hasala (BOZP) má jasno v tom, co se lepit a zakrývat nesmí. Trochu disciplíny teď ušetří fleky na schodech a nervy potom.",
    tips: [
      "Vymyslete jednu zastřešující ideu/téma a podle ní celou výzdobu sjednoťte - ať to drží pohromadě a netáhne každý jiným směrem.",
      "Rozdělte školu na zóny pod společnou ideou a každou zónu svěřte jiné skupince - každý si tak vezme svůj kus za svůj.",
      "Dejte každé skupince budget. Co je nad budget, jde k diskuzi se zbytkem týmu.",
      "Plán výzdoby dejte předem ke schválení tajemníkovi a poučte se s panem Hasalou (BOZP) o tom, co se smí a nesmí.",
      "NELEPIT nic na dveře, okna, rámy oken a sochy.",
      "Nezakrývejte ani nepolepujte cedulky a značení únikových cest, prodejní automaty, elektrické skříně, hydranty a hasicí přístroje (hasicí přístroje se ani nepřemisťují), vrátnici a auta.",
      "Pozor na barevné izolepy - barva zůstává na povrchu a dělá fleky (typicky na schodech). Raději se jim vyhněte.",
      "Hlídejte chráněné únikové cesty a průchodnost - hlavně schodiště v budově B. Zachovejte průchod minimálně 2 m a výtahy nechte volné.",
      "Dávejte přednost nehořlavým materiálům.",
      "Zdobit stačí 1-2 dny předem - není potřeba se s tím honit dlouho dopředu.",
      "Na vrátnici si dopředu domluvte pozdější zamykání nebo zdobení o víkendu, ať máte na výzdobu klid a čas.",
      "Materiál na výzdobu skladujte v Arše nebo kotelně - obojí je uzamykatelné.",
    ],
    callouts: [
      { kind: "kontakt", text: "Plán výzdoby schvaluje tajemník; pravidla BOZP (co se nesmí lepit a zakrývat) konzultujte s panem Hasalou." },
      { kind: "pozor", text: "Barevné izolepy zanechávají barvu na povrchu a dělají fleky - hlavně na schodech. A nikdy nic nelepte na cedulky a značení únikovek, hydranty ani hasicí přístroje." },
      { kind: "tip", text: "Skladujte v uzamykatelné Arše nebo kotelně a na vrátnici si předem domluvte pozdější zamykání či zdobení o víkendu - 1-2 dny předem bohatě stačí." },
    ],
  },
  {
    id: "prvaci",
    emoji: "🐣",
    title: "Prváci a maskot",
    intro:
      "Prváci jsou palivo Mařeny. Pravidlo zní jasně: první slovo, které na fakultě uslyší, musí být Mařena. Valte na ně informace ze všech stran, ať od první minuty vědí, o co jde, a postupně z nich vyrostou ti, kdo ponesou maskota městem a klaní se u staveb. Tahle sekce shrnuje, jak je odchytit už u zápisu, jak je celý týden držet v zápřahu a jak je v pořádku (a hlavně najedené) dopravit až na Flédu.",
    tips: [
      "První slovo na fakultě musí být Mařena - valte informace ze všech stran, ať prváci hned vědí, o co jde. Motto ročníku 2024: \"Kolik Mařeny je dost Mařeny? Mařeny není nikdy dost.\"",
      "Odchyťte je už u zápisu prváků (probíhá od června) - kontaktní cesta na zápisu vede přes Forteho na Doubravovou.",
      "První den mají prváci dopolední program v aule - využijte ho na úvodní prezentaci Mařeny. Slot v aule si domluvte se Soňou Lisoňovou (nejdůležitější člověk z fakulty, vše zařídí - tablety, dataprojektory, držáky na telefony, banner na fasádu).",
      "Při prezentaci i průběžně cpěte QR kód na instagram, ať vás prváci sledují a mají denní program po ruce.",
      "Opakujte prvákům dokola, kde a kdy je co k jídlu: snídaně, obědy a večerní programy na dvoře. Bar i výdej jídla jsou na dvoře, Archa slouží jen jako zázemí.",
      "Motivujte je k chození na přednášky systémem razítek a odměn.",
      "Maskot se tradičně nosí v průvodu městem (poslední den akce) a nesou ho právě prváci - musí doputovat až na Flédu.",
      "Během průvodu se zastavuje u významných staveb a prváci se u nich klaní; chodí se co nejvíc po chodnících.",
      "Průvod zasahuje do cvičení - dopředu domluvte s vyučujícími, ať prváky omluví (osvědčily se buchty, kafe a sklopená hlava), a prvákům řekněte, že jsou omluveni.",
      "Prváky nechte běhat a nalévat od cca 16:30; v roce 2024 byl odchod 17:20 a příchod na Flédu 19:00 (mapy hlásily ~1 h 14 min trasy). Megafon na hypování fakulta má a půjčí; petky na míchání drinků pro prváky se cestou odkládají.",
      "DŮLEŽITÉ - prváky připravte, ať se najedí PŘED Flédou. V roce 2024 se jich hodně ožralo na průvodu, ještě než vůbec začala hrát hudba. Domluvte jídlo přímo s Flédou, nebo jim na místo propašujte kebab.",
      "Na Flédě se prváci tradičně pasují (jednotlivě nebo po skupinkách). V roce 2024 vynechali mokrý křest (mouka, kečup) a Fléda z toho měla radost; osvědčilo se pasování světelným mečem a panák zelené - prvácké ohlasy byly výborné.",
    ],
    callouts: [
      { kind: "kontakt", text: "Zápis prváků: Forte → Doubravová. Slot pro úvodní prezentaci v aule první den řeší Soňa Lisoňová." },
      { kind: "tip", text: "Merch shop spusťte 10. září a uzavřete 19. září - prváci během prvních tří dnů pochopí, že merch potřebují. Zdůrazněte vyzvednutí NA DVOŘE." },
      { kind: "pozor", text: "Prváci musí jíst! Před průvodem i před Flédou je nakrmte, jinak skončí ožralí dřív, než začne program." },
    ],
  },
  {
    id: "merch",
    emoji: "👕",
    title: "Merch",
    intro:
      "Merch je polovina festivalové identity a druhá polovina rozpočtového polštáře. Ročník 2024 si vyzkoušel předobjednávky přes Shopify a vyplatilo se to: přehledné objednávky, žádný chaos a tisknete jen to, co si lidi reálně koupí. Klíč je spustit shop ve správné chvíli (prváci do tří dnů pochopí, že merch potřebují) a hlavně všem nahlas opakovat, že se vyzvedává NA DVOŘE, ne posílá domů. A než to celé pustíte mezi lidi, objednejte si jeden kus sami a zkontrolujte, že celý proces šlape.",
    tips: [
      "Předobjednávky řešte přes Shopify - objednávky jsou pak přehledné a máte je pod kontrolou. Počítejte s předplatným cca 1 euro za první měsíc a poté cca 13 euro.",
      "Založte si samostatný email jen na předobjednávky merche, ať se to nemíchá s ostatní komunikací.",
      "Najděte si flexibilní tiskárnu, která jede ve stylu nabídka-poptávka - levnou a ochotnou. Tisknete podle reálné poptávky, ne na sklad.",
      "Shop spusťte kolem 10. září a zavřete cca 19. září. Prváci první tři dny pochopí, že merch potřebují, takže není kam spěchat se zavíráním.",
      "Po uzavření shopu udělejte dotisk podle poptávky - dotiskujete jen to, co se reálně objednalo.",
      "Hlasitě a opakovaně zdůrazňujte, že se merch vyzvedává NA DVOŘE. V roce 2024 někteří lidi čekali, že jim to přijde poštou domů.",
      "Před spuštěním shopu si udělejte zkušební objednávku sami na sebe - ověříte, že celý proces (objednávka, platba, potvrzení) funguje, jak má.",
      "Merch se vydával a prodával přímo na velkém baru na dvoře, kde se zároveň vařilo, točilo pivo a prodávaly lístky na Flédu - vše na jednom místě se osvědčilo.",
      "Platby řešte přes QR i hotově. Na QR fungoval AlienPay z dílny pana Vostala (webová stránka generuje QR kódy, částka se mění na straně kasy) - ochotně to nasdílí.",
      "Dohodněte se, že merch si platí všichni z organizace stejně jako pití a jídlo - ať v penězích není bordel.",
      "Grafiku merche ať dělá člověk, který zároveň řeší socky nebo aspoň vytvoří šablony - design držte v jedné ruce.",
      "Pozor na školní řád: oficiálně se ve škole prodávat nesmí. Prodej řešte podobně jako u baru (např. přes žetony / na dvoře), ne jako klasický pultový prodej v budově.",
    ],
    callouts: [
      { kind: "tip", text: "Nejdřív zkušební objednávka pro sebe, až pak spuštění pro lidi. Ušetří vám to trapas, když by něco v procesu nešlapalo." },
      { kind: "pozor", text: "Vyzvednutí je NA DVOŘE, ne zaslání domů. Napište to do popisku produktu, do potvrzení objednávky i na socky - jinak vám lidi budou psát, kde mají balík." },
      { kind: "kontakt", text: "QR platby: AlienPay z dílny pana Vostala (generuje QR kódy, částka se mění na straně kasy) - ochotně nasdílí." },
    ],
  },
  {
    id: "bar",
    emoji: "🍺",
    title: "Bar, Archa a jídlo",
    intro:
      "Vůbec nejlepší rozhodnutí ročníku 2024 byl jeden velký bar na dvoře, kde se sešlo úplně všechno: vařilo se, točilo pivo i limo, vydával a prodával merch i lístky na Flédu. Všechno na jednom místě, žádné běhání mezi stanovišti. Archa zůstala jako zázemí (kuchyň), ale jako prostor pro program ji rozhodně nedoporučujeme. A jídlo s pitím? To si musí vzít na starost někdo opravdu kompetentní, protože nákupy, auto a vaření pro stovku lidí nejsou žádná legrace.",
    tips: [
      "Postavte JEDEN velký bar na dvoře jako společný hub: vaří se tu, točí pivo a limo, vydává a prodává merch a prodávají lístky na Flédu. Vše na jednom místě je osvědčená klasika. Bar v Arše by nefungoval (moc lidí).",
      "Udělejte rozvrh, kdo kdy stojí za barem (vždy aspoň 2 lidi za pultem, klidně se střídejte), ale lidem nevadilo stát tam celý večer - venku o nic nepřijdou.",
      "Archu používejte JEN jako zázemí: vařila se tam většina jídel, na baru se pak jen dodělávalo a přihřívalo. Na konci Archu kompletně ukliďte.",
      "Program v Arše NEDOPORUČUJEME: party v Arše skončila tím, že ukradli tablet a DJovi světla. Archa ať zůstane zavřené zázemí.",
      "Pípu si půjčte větší, líp chladí = víc piva (info má Rado). Sudy jsou flexibilní - co nevytočíte, dodavatel si odveze. Točili Zonku (Palaščák drink: bezinka + vodka).",
      "Kasa jela na tabletech (tablety i držáky na telefony shání Soňa Lisoňová ze školy). Platilo se QR i hotově - hotovostní kasu nechte se základem na další den jak v hospodě.",
      "Kupte kelímky - skla je nedostatek a po minulých ročnících ho hodně zbylo. Várnice se hodí na svařák nebo mošt na chladné dny.",
      "Jídlo a pití musí mít na starost někdo vysoce kompetentní - bez toho to nejde.",
      "Velké nákupy dělejte v Makru (i jednorázové nádobí) a nejdřív koukněte, co zbylo po předchozím ročníku. NUTNOST AUTA - bez auta ani ránu.",
      "Obědy: mějte dostatek nádobí (naběračky, míchačky, mísy) a dobré plotýnky. Začněte vařit brzo, klidně v 8 nebo dřív, a střídejte se, ať nevaří celý týden jeden člověk. Vařilo se do cca 100 porcí + polévka.",
      "Polévky jsou fajn (chce to ohřívací hrnec). Denní menu zveřejňujte, hlavně obědy - lepší je vydávat venku.",
      "Alkohol: ve školním řádu je zákaz konzumace (a prodej alkoholu na tom nebude líp). Adéla k tomu dodává: kontrola nikdy nepřišla, a kdyby přišla, je to problém školy, ne náš.",
      "Domluvte se, že si všichni platí všechno (pití, jídlo, merch), ať v penězích není bordel.",
    ],
    callouts: [
      { kind: "pozor", text: "Program v Arše NEDOPORUČUJEME - při party v Arše ukradli tablet a DJovi světla. Archa ať slouží jen jako uzamčené zázemí pro kuchyň." },
      { kind: "kontakt", text: "Pípa: info má Rado. Tablety na kasu, držáky a další techniku zařídí Soňa Lisoňová (\"teta\") ze školy." },
      { kind: "tip", text: "Nákupy řešte v Makru (vč. jednorázového nádobí) a auto je absolutní nutnost - bez něj se velké nákupy ani várnice nepřevezou." },
    ],
  },
  {
    id: "pruvod",
    emoji: "🚩",
    title: "Průvod městem",
    intro:
      "Poslední den Mařeny vyrazí celá fakulta v igelitových pytlích ulicemi Brna a doputuje na Flédu, kde se křtí prváci. Vypadá to jako sranda (a je), jenže před tím vás čeká pořádná porce zasrané byrokracie, takže ji rozjeďte s velkým předstihem. Klíč je sepsat trasu ulici po ulici, projít všechny úřady a institucemi a všechno nahlásit minimálně 30 dní předem. Tady je celý postup i s kontakty a osvědčenými časy z ročníku 2024.",
    tips: [
      "BYROKRACIE NEJDŘÍV: zařizujte všechno s velkým předstihem. Začněte tím, že sepíšete trasu průvodu ulici po ulici. Bez detailní trasy se nikam nepohnete.",
      "Trasa míří na odbor dopravy, Měnínská 4 - paní Lenka Polánková (milá, Mařenu zná, sama komunikuje s městskými částmi Brna). V roce 2024 trasa zasáhla 3 části Brna.",
      "Sled institucí: povolení od dotčených městských částí → BKOM → DPMB → policie (Státní/Městská) nahlásit průvod (samotný doprovod možná hlásit nemusíte). Vše ohlásit jako kulturní akci a minimálně 30 dní předem.",
      "Platí se správní poplatek. Kdo akci zařizuje, ten za průvod zodpovídá (uvádí se jeho telefon).",
      "Zprávy posílejte za sebe / za tým Mařeny, NE za fakultu - je to studentská akce, fakulta jen zastřešuje.",
      "Vesty seženete od školníků (mají jich spoustu pro pana Chybíka na exkurze). Minimálně 2 označení organizátoři v oranžových vestách, v Arše jich bývá taky plno.",
      "Megafon na hypování mají také školníci, ochotně ho pošlou dál. Vezměte plastové petky na míchání drinků pro prváky a igelitové pytle - na dvoře se studenti do pytlů oblékají a začíná se pít.",
      "Průvod zasahuje do odpoledních cvičení: domluvte s vyučujícími, ať prváky omluví (osvědčily se buchty, kafe a sklopená hlava) a hlavně řekněte prvákům, že jsou omluveni.",
      "BACHA: organizátoři ať pijí až před Lužánkami - předtím není kde se ztratit a musíte fungovat.",
      "Tradičně se nese maskot/maskot, který musí doputovat až na Flédu (nesou ho prváci). U významných staveb se průvod zastavuje a prváci se klaní. Choďte co nejvíc po chodnících.",
      "Časový plán z roku 2024 (funguje): trasa cca 1h14m průvodu (změřte v mapách), prváky nechte běhat a nalévat od 16:30, odchod v 17:20, příchod na Flédu v 19:00 a hned křest. Od příchodu byla zhruba hodina, než hrál první DJ - bohatě stačila.",
      "Pošlete někoho napřed na Flédu (3 lidi, 2 by stačili) připravit křest a přivítat kapely.",
      "Prváky připravte, ať se najedí předem - hodně se jich na průvodu ožralo a na Flédě ještě nehrála hudba. Domluvte jídlo s Flédou, nebo propašujte kebab.",
    ],
    callouts: [
      { kind: "kontakt", text: "Odbor dopravy, Měnínská 4 - pí Lenka Polánková. Zná Mařenu a sama komunikuje s městskými částmi Brna." },
      { kind: "pozor", text: "Organizátoři pijí až před Lužánkami - předtím se nemáte kde ztratit a musíte mít vše pod kontrolou." },
      { kind: "tip", text: "Vše hlaste jako kulturní akci minimálně 30 dní předem a počítejte se správním poplatkem. Sled: městské části → BKOM → DPMB → policie." },
    ],
  },
  {
    id: "fleda",
    emoji: "🌟",
    title: "Fléda a křest",
    intro:
      "Vyvrcholení celé Mařeny. Po průvodu městem dorazí dav do klubu Fléda, kde se pasují prváci a slavnostně se ukončí celý festival. Je to ta nejpamátnější část akce, ale taky ta, kterou si nesmíte podělat na poslední chvíli, takže klub zamlouvejte hned na začátku a Flédě se pravidelně připomínejte. Ročník 2023 vypekli tím, že o sobě nedali vědět, tak ať to není i váš příběh.",
    tips: [
      "Zamluvte Flédu co nejdřív (klidně už na přelomu prosince a ledna) a vyřešte hlavně datum. Majitelé klubu už o tradici pasování studentů prvního ročníku vědí.",
      "Pronájem řešte od 20:00 do 04:00, ráno máte čas do 11:00 na odvoz věcí. Sepište nájemní smlouvu, cena vychází zhruba na 30-35 000 Kč.",
      "Pošlete zvukaři ridery (zvukové požadavky kapel) a seznam kapel. PRAVIDELNĚ SE FLÉDĚ PŘIPOMÍNEJTE - ročník 2023 vypekli, tak nenechte nic na náhodě.",
      "Lístky prodávejte co nejdřív, klidně už od půlky týdne. V Arše a v knihovně FA cca 150 Kč, na místě dráž cca 200 Kč. Tisklo se cca 400-700 lístků (kapacita Flédy je 700) - počítejte s tím, že evidence prodaných lístků se těžko zvládá.",
      "Absolventi a vyšší ročníky chtějí vědět, kdy přesně je křest - nasdílejte jim to, přijdou.",
      "Den předem nebo ráno běžte zdobit a připravovat podium: obalte fóliemi (malířská fólie) podium i stěny kolem, a plochu zhruba 1-1,5 m před podiem. Připravte si hudební podkres na pasování.",
      "Pasuje se jednotlivě nebo po skupinkách. Mokrá varianta: lije a sype se cokoliv - mouka, vločky, kečup, hořčice, voda. NIKDY OCET A VOŇAVKY. Na posilnění panáky.",
      "Suchá varianta funguje taky: ročník 2024 řekl Flédě, že nebude mokrý křest (žádná mouka, kečup), z čehož měl klub radost - pasovalo se světelným mečem a panákem zelené a prváckým ohlasům to slušelo.",
      "Eliminujte roznášení směsi po klubu - igelity sundejte hned pod podiem, jakmile pasování skončí.",
      "Po křtu ukliďte hlavní prostor a během úklidu zajistěte hudbu na malém podiu, ať párty neumře.",
      "POZOR: Fléda má svou security a nerada pouští lidi ven. Upozorněte na to dopředu a hlavně připravte prváky. Při zařizování se zkuste zeptat, jestli to jde nějak změnit.",
      "Prváky připravte, ať se najedí PŘED Flédou - hodně se jich na průvodu ožralo a na Flédě ještě dlouho nehrála hudba. Domluvte jídlo s Flédou, nebo propašujte kebab.",
      "Pošlete napřed 2-3 lidi (2 stačí), kteří na Flédě připraví křest a přivítají kapely. Po příchodu průvodu se křtí hned - hodina než hrál první DJ bohatě stačila.",
    ],
    callouts: [
      { kind: "pozor", text: "Mokrý křest: mouka, vločky, kečup, hořčice, voda ANO. Ocet a voňavky NIKDY. Suchá varianta (světelný meč + panák) funguje stejně dobře a Fléda ji ocení." },
      { kind: "tip", text: "Hned po pasování sundejte igelity pod podiem, ať se směs neroznáší po celém klubu - ušetříte si pak hromadu úklidu." },
      { kind: "kontakt", text: "Flédě se PRAVIDELNĚ připomínejte (seznam kapel, ridery zvukaři). Ročník 2023 vypekli tím, že o sobě nedali vědět." },
    ],
  },
  {
    id: "bozp",
    emoji: "🦺",
    title: "Provoz a bezpečnost (BOZP)",
    intro:
      "Než začnete cokoliv lepit, věšet a stavět, je tu pár pravidel od vedení — konkrétně od pana Hasaly, který má na fakultě na starost BOZP. Nejsou to buzerace pro buzeraci: jde o únikové cesty, hasičáky a o to, aby vám nikdo nemusel Mařenu zatrhnout. Dobrá zpráva: když se domluvíte dopředu a podepíšete papíry, je vedení nakloněné. Horší zpráva: vrátný vás o půlnoci stejně vyhodí, tak si načasování pohlídejte.",
    tips: [
      "Nikdy nepolepujte ani nezakrývejte: sochy, prodejní automaty, elektrické skříně, hydranty, hasicí přístroje, jakékoliv dveře, vrátnici, auta a schodiště.",
      "Hasicí přístroje se ani nepřemisťují — musí zůstat tam, kde jsou.",
      "Nelepte nic na dveře, okna, rámy oken, sochy ani na cedulky únikových cest. Pozor na barevné izolepy — barva zůstane na povrchu a dělá fleky (typicky na schodech).",
      "Hlídejte chráněné únikové cesty a jejich průchodnost (hlavně schodiště v budově B). Průchod musí být minimálně 2 m široký.",
      "Na výzdobu používejte ideálně nehořlavé materiály a výtahy nechte volné.",
      "Plán výzdoby dejte předem „ke schválení“ tajemníkovi a celkově se s výzdobou „poučte panem Hasalou“.",
      "Provozní režim: 6:00–22:00 fakulta + nádvoří, 22:00–01:00 už jen ve studentském klubu. Po 22:00 se venku nekoncertuje (noční klid).",
      "Školu lze výjimečně v rámci Mařeny obývat do 24:00–01:00 (jindy 20:00–22:00), ale děkan kvůli tomu musí napsat na vrátnici o prodlouženém otevření — jinak vás vrátný ve standardní čas vyhodí.",
      "Příjezdy externistů a přednášejících hlaste předem na vrátnici (e-mail na vrátnici + kopie tajemníkovi).",
      "Auto na dvůr potřebujete na nákupy a převozy — parkování na dvoře si dopředu domluvte na vrátnici.",
      "Všichni organizátoři podepíší formulář BOZP, který rozešle pan Hasala.",
    ],
    callouts: [
      { kind: "pozor", text: "Podle školního řádu je na fakultě zákaz konzumace i prodeje alkoholu. Ročníku 2024 kontrola nikdy nepřišla, ale kdyby přišla, je to problém školy, ne váš — riziko ale berte vážně." },
      { kind: "kontakt", text: "Pan Hasala (BOZP, vedení) — rozesílá formulář BOZP k podpisu a radí s výzdobou, ať neporušíte pravidla." },
      { kind: "tip", text: "Vrátný vyhazuje o půlnoci — poslední odchází až po zametení dvora, tak s tím počítejte při plánování úklidu." },
    ],
  },
  {
    id: "vy",
    emoji: "💛",
    title: "Vy během festivalu",
    intro:
      "Takže jste se (snad dobrovolně) rozhodli zorganizovat tu nejlepší, nejšílenější a nejnáročnější studentskou akci na fakultě. Tahle sekce není o programu, kapelách ani o průvodu - je o vás. Mařena je půl roku příprav, stovky emailů a po startu i pořádná fyzická rachota, takže než se do toho vrhnete, pár věcí, co vám zachrání nervy i spánek. A hlavně: nezapomeňte, že je to sranda.",
    tips: [
      "Připravte se na to, že je Mařena extrémně psychicky náročná: půl roku plánování, stovky emailů, složky na Google disku - a jakmile festival odstartuje, přidá se k tomu i náročnost fyzická.",
      "Den začíná brzo: první lidi ráno chystají snídaně. Přes celý den jedete na komunikaci - se studenty, vedením, přednášejícími i kapelami. A poslední odcházíte až po zametení dvora (vrátný stejně vyhodí o půlnoci).",
      "Bez auta ani ránu. Hodí se na velké nákupy (Makro - jídlo, pití i jednorázové nádobí) i na provoz během týdne. Parkování na dvoře si dopředu domluvte na vrátnici.",
      "Domluvte si směny - kdo kdy stojí za barem, kdo vaří, kdo řeší co. Rozvrh za barem fungoval, a lidem ani nevadilo trčet tam celý večer, protože venku na dvoře o nic nepřišli.",
      "Zařiďte co nejvíc věcí dopředu - hlavně grafiky a posty (programy, medailonky přednášejících). Tým 2024 to neudělal, nestíhal a na medailonky úplně zapomněl. Připravené příspěvky ušetří čas i nervy a hlavně vám dají šanci se vyspat.",
      "Delegujte. Spousta lidí předem řekla, že organizovat nechtějí, ale při Mařeně pomůžou - a pomohli, bylo to super. Nebojte se rozdat úkoly.",
      "Jezte víc než jen oběd a pivo. Během dne na sebe snadno zapomenete, ale na týden v tomhle tempu to nestačí.",
      "Vyspěte se. Zní to banálně, ale při půlroce příprav a týdnu na nohách je spánek to první, co obětujete - a to se vám vymstí.",
      "Finance ať řeší jedna důvěryhodná osoba (ta, na kterou je psaný účet), ne celá skupina. Méně bordelu, jasná zodpovědnost.",
      "U průvodu platí: kdo ho zařizuje, ten za něj zodpovídá (a má u sebe telefon). A organizátoři ať pijí až před Lužánkami - předtím není kde se v davu ztratit.",
      "Všichni organizátoři podepíší formulář BOZP (zašle pan Hasala). Provozní režim: 6-22 fakulta a nádvoří, 22-01 ve studentském klubu.",
      "A nakonec to nejdůležitější - užijte si to. Je to sranda, je to jednou za studium, a stojí to za to.",
    ],
    callouts: [
      { kind: "tip", text: "Nejdůležitější člověk z fakulty je Soňa Lisoňová - milá, ochotná, vše zařídí (tablety, dataprojektory, zvukař na celý festival placený školou, banner na fasádu). Supaspicybois jí říkají teta. Ozvěte se jí, až budete mít datum a nahozený program." },
      { kind: "pozor", text: "Party v Arše = ukradli tablet a DJova světla. Program v Arše proto NEDOPORUČUJEME - držte ji jako zázemí a kompletně ji ukliďte." },
      { kind: "kontakt", text: "Auto je nutnost - velké nákupy řešte v Makru a koukněte, co po nás zbylo. Parkování na dvoře předem domluvit na vrátnici." },
    ],
  },
];
